FROM python:3.8-slim-buster

WORKDIR /container

COPY requirements.txt requirements.txt

RUN pip3 install -r requirements.txt
RUN pip install ipython
RUN pip install -i https://test.pypi.org/simple/ bigtorch-denissimo

COPY data_mnist data_mnist
COPY big_torch_neptune.py big_torch_neptune.py
COPY runner.py runner.py
