name: 
  Docker Publish
  # BT Publish

on: push

jobs:
  # build-n-publish-pypi:
  #   name: BT Publish
  #   runs-on: ubuntu-18.04

  #   steps:
  #   - uses: actions/checkout@master
  #   - name: Set up Python 3.9
  #     uses: actions/setup-python@v1
  #     with:
  #       python-version: 3.9

  #   - name: Install pypa/build
  #     run: >-
  #       python -m
  #       pip install
  #       build
  #       --user
        
  #   - name: Build a binary wheel and a source tarball
  #     run: >-
  #       python -m
  #       build
  #       --sdist
  #       --wheel
  #       --outdir dist/
  #       .

    - name: Publish distribution 📦 to Test PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.PYPI_TEST_PUBLISH_TOKEN }}
        repository_url: https://test.pypi.org/legacy/

  build-n-publish-docker:
    name: Docker Publish
    runs-on: ubuntu-latest
    # needs: build-n-publish-pypi
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/checkout@v2
      - name: Build the stack
        run: docker build --pull -f "container/Dockerfile.build" -t big-torch:latest "container" 
      - name: Publish to dockerhub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/big-torch:latest